openapi: 3.0.0
info:
  title: Invoice Service
  description: MondiraSimonCapstone
  version: 0.0.1
servers: 
  - url: http://localhost:7002
    description: Invoice web service
paths: 
  /invoices:
    post:
      summary: Creates a new Invoice entry with the given information
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Invoice'
      responses:
        '201':
          description: An Invoice object
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Invoice'
        '400':
          description: Invalid request syntax.
        '422':
          description: Incomplete LevelUp information. Some required fields missing.
    
    get:
      summary: get All Invoice Details
      responses:
        '200':
          description: Generate an Invoice list JSON object.
          content:
            application/json:
              schema:
                type: object
                items:
                  $ref: '#/components/schemas/Invoice'
                  
  /invoices/{id}:            
    get:
      summary: get Invoice by id
      parameters: 
        - name: id
          in: path
          required: true
          description: id of the Invoice
          schema:
            type: integer
            format: int64
            minimum: 1
      responses:
        '200':
          description: Generate an Invoice list JSON object.
          content:
            application/json:
              schema:
                type: object
                items:
                  $ref: '#/components/schemas/Invoice'
        '400':
          description: Entity not found
  
    put:
      summary: Updated the entry for the Invoice with the given ID.
      parameters: 
        - name: id
          in: path
          required: true
          description: ID of the Level Up you would like to update.
          schema:
            type: integer
            format: int64
            minimum: 1
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Invoice'
      responses:
        '200':
          description: Invoice successfully updated.
        '422':
          description: Invoice ID on path must match the ID in the Invoice object.
        '400':
          description: Entity not found 
          
    delete:
      summary: Deletes the entry for the Invoice up with the given ID.
      parameters: 
        - name: id
          in: path
          required: true
          description: ID of the Invoice you would like to delete.
          schema:
            type: integer
            format: int64
            minimum: 1
      responses:
        '200':
          description: Invoice successfully deleted
        '400':
          description: Entity not found
          
  /invoices/{customerId}:            
    get:
      summary: get Invoice by customer ID
      parameters: 
        - name: customerId
          in: path
          required: true
          description: id of the customer
          schema:
            type: integer
            format: int64
            minimum: 1
      responses:
        '200':
          description: Generate a Invoice list JSON object.
          content:
            application/json:
              schema:
                type: object
                items:
                  $ref: '#/components/schemas/Invoice'
        '400':
          description: Entity not found   
  
 
    
components:
  schemas:
    Invoice:
      type: object
      properties:
        invoiceId:
          type: number
        customerId:
          type: number
        purchaseDate:
          type: object # Date
    
          
    